service: authflow-api

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  environment:
    USERS_TABLE: ${self:service}-users-${self:provider.stage}
    JWT_SECRET: ${ssm:/authflow/jwt-secret}
    SES_FROM: no-reply@example.com
    BASE_URL: https://${self:provider.stage}.api.authflow.example.com
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
      Resource:
        - !GetAtt UsersTable.Arn
        - !Sub ${UsersTable.Arn}/index/*
    - Effect: Allow
      Action:
        - ses:SendEmail
        - ses:SendRawEmail
      Resource: "*"

functions:
  register:
    handler: src/handlers/register.handler
    events:
      - http:
          path: /users
          method: post
          cors: true

  confirm:
    handler: src/handlers/confirm.handler
    events:
      - http:
          path: /users/confirm
          method: get
          cors: true

  login:
    handler: src/handlers/login.handler
    events:
      - http:
          path: /auth/login
          method: post
          cors: true

  forgotPassword:
    handler: src/handlers/forgotPassword.handler
    events:
      - http:
          path: /auth/forgot-password
          method: post
          cors: true

  me:
    handler: src/handlers/me.handler
    events:
      - http:
          path: /auth/me
          method: get
          cors: true
          authorizer: aws_iam

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.USERS_TABLE}
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: UsernameIndex
            KeySchema:
              - AttributeName: username
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
